### ISSUE TITLE
custom props

### ISSUE THREAD

**Issue by nathnolt** [Freak613/domc#12]
I'm trying to make custom props appear in my component, using domc( with my markup including a call to that custom element with a specific prop value. ) I don't get it. all I get is undefined, or the default value if I don't specify an overwrite value.

**Comment by Freak613** [comment]
Setting dom properties is not supported at the moment, unfortunately library was not designed with custom elements in mind. I will keep this issue open and keep an eye on it.

Meanwhile, I can direct you to another library, that I'm working on currently: https://github.com/Freak613/1more
It has property-first approach, so your use case should be supported. 
But keep in mind that it is also work-in-progress, so use it only for fun projects.

**Comment by nathnolt** [comment]
Thanks for the help 😊
