### ISSUE TITLE
The WICG likes your API

### ISSUE THREAD

**Issue by shannonmoeller** [Freak613/domc#13]
Did the WICG lift your API for a native template proposal or did you borrow theirs? Just curious.

Yours:
![image](https://user-images.githubusercontent.com/155164/117852807-f56cca80-b244-11eb-8a26-f00c0b4b40c3.png)

Theirs:
![image](https://user-images.githubusercontent.com/155164/117852866-061d4080-b245-11eb-925f-fcf0715ee18b.png)

https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md#31-basics

**Comment by Freak613** [comment]
I took their API for inspiration 2 years ago and, yes, it does look like implementing update part of it.
But there are differences. Where they use custom template syntax for looping and conditionals, this lib use directives like Vue (only for loops now).
