### ISSUE TITLE
[FR] please add domc and stage0 min v. to cdnjs.com or write sizes in doc

### ISSUE THREAD

**Issue by trsh** [Freak613/domc#7]
Speed is great, but another important factor in choosing JS framework is it's size. I could not find any info on that. So literally have to try :( .. and with all minimization, uglyfuing etc, its not such a small thing todo for every guy why's interested in this tech.

**Comment by Freak613** [comment]
Yeah, it looks like having overweight.
`minified-size` showing 2.33Kb for index.js and 1.08Kb for vFor.js that can be considered as average setup.
Same size as preact and 2x hyperapp.
Size was not the main point during development though.

**Comment by trsh** [comment]
@Freak613 thanks, could u do same for stage0?

**Comment by Freak613** [comment]
Sure.

I'll try to think about size.

**Comment by trsh** [comment]
@Freak613 thanks. Feel free close this issue when appropriate.
